"""add seo meta fields and updated_at

Revision ID: 7490605ecb91
Revises: a7c36df311aa
Create Date: 2026-09-19 16:13:31.308569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7490605ecb91'
down_revision: Union[str, None] = 'a7c36df311aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('meta_title', sa.String(length=70), nullable=True))
    op.add_column('products', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('states', sa.Column('meta_title', sa.String(length=70), nullable=True))
    op.add_column('states', sa.Column('meta_description', sa.String(length=160), nullable=True))
    op.add_column('states', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('states', 'updated_at')
    op.drop_column('states', 'meta_description')
    op.drop_column('states', 'meta_title')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'meta_description')
    op.drop_column('products', 'meta_title')
    # ### end Alembic commands ###
